Repository payper-devs/payper-client, pull requests merged in 2025-08, with the labels that each got.

#150 [FEATURE #144}: 페이지별 BottomNavigation 추가
  src/components/common/BottomNavigation.vue
  src/pages/HomePage.vue
  src/pages/MyCardPage.vue
  src/pages/ProfilePage.vue
  src/pages/search/CheckSearchPage.vue
  src/pages/search/CreditSearchPage.vue
  src/pages/search/PartnerSearchPage.vue
Labels: ✨ Feature

#162 [REFACTOR #157]: 연회비 타입 삭제 및 카드 타입 수정
  src/mocks/data/mockCard.ts
  src/mocks/data/mockCards.ts
  src/mocks/data/mockPartner.ts
  src/mocks/data/mockPartners.ts
  src/pages/CardDetailsPage.vue
  src/tests/pages/MyCardPage.test.ts
  src/types/AnnualCost.ts
  src/types/Card.ts
Labels: ⚒️ Refactor

#172 [FEATURE #170]: Agree에 라우터 추가
  src/components/home/HomeSearchBar.vue
  src/pages/AgreePage.vue
  src/pages/HomePage.vue
Labels: ✨ Feature

#173 [REFACTOR #165]: 새로 고침 버튼 lucide-vue-next으로 추가
  src/pages/HomePage.vue
Labels: ⚒️ Refactor

#179 [REFACTOR #178]: 홈페이지 CSS 변경
  src/components/home/HomeSearchBar.vue
Labels: ⚒️ Refactor

#184 [REFACTOR #182]: 서버 Base URL을 환경 변수로 관리
  src/api/axios.ts
Labels: ⚒️ Refactor

#195 [BUG #194]: kakao is not defined 해결
  src/pages/HomePage.vue
  vite.config.ts
Labels: 🐞 Bug

#201 [FEATURE #200]: msw 동작 여부 .env로 관리
  src/main.ts
Labels: ✨ Feature, 🧪 Test

#199 [REFACTOR #197]: 내 위치 마커 이미지 수정
  src/assets/MAP_MARKER.png
Labels: ⚒️ Refactor

#203 [REFACTOR #202]: card api수정 및 찾기 페이지api연동
  src/api/card.api.ts
  src/components/cardlist/CardItem.vue
  src/pages/search/CheckSearchPage.vue
  src/pages/search/CreditSearchPage.vue
  src/pages/search/PartnerSearchPage.vue
Labels: ⚒️ Refactor

#204 [FEATURE #196]: 마커 위에 마우스 올리면 상세정보 표시
  src/mocks/data/mockCards.ts
  src/mocks/data/mockPartners.ts
  src/pages/HomePage.vue
  src/types/Positions.ts
Labels: ✨ Feature

#208 [REFACTOR #207]: 응답 객체 수정
  src/components/card/BenefitItem.vue
  src/components/cardlist/CardItem.vue
  src/components/partner/PartnerCard.vue
  src/mocks/data/mockBenefit.ts
  src/mocks/data/mockBenefits.ts
  src/mocks/data/mockCard.ts
  src/mocks/data/mockCards.ts
  src/mocks/data/mockGrades.ts
  src/mocks/data/mockPartner.ts
  src/mocks/data/mockPartners.ts
  src/pages/CardDetailsPage.vue
  src/pages/search/PartnerSearchPage.vue
  src/tests/pages/MyCardPage.test.ts
  src/types/Benefit.ts
  src/types/BenefitGrade.ts
  src/types/Card.ts
  src/types/Discount.ts
  src/types/Grade.ts
Labels: ⚒️ Refactor

#214 [BUG #206]: 카드리스트 화면 짤림 수정
  src/assets/main.css
  src/pages/search/CheckSearchPage.vue
Labels: 🐞 Bug

#222 [REFACTOR #215]: 검색페이지 컴포넌트화
  src/components/search/SelectDrawerButton.vue
  src/components/searchpage/CardAccordionList.vue
  src/components/searchpage/FilterSection.vue
  src/components/searchpage/SearchInput.vue
  src/components/searchpage/SearchTabs.vue
  src/components/searchpage/SelectedTags.vue
  src/components/searchpage/SortSelect.vue
  src/pages/search/CheckSearchPage.vue
  src/pages/search/CreditSearchPage.vue
  src/pages/search/PartnerSearchPage.vue
Labels: ⚒️ Refactor

#236 [REFACTOR #235]: 응답객체 수정에 따른 코드 수정(초기 수정)
  src/components/card/BenefitItem.vue
  src/components/cardlist/CardItem.vue
  src/components/home/PartnerDrawerItem.vue
  src/components/partner/PartnerCard.vue
  src/mocks/data/mockBenefit.ts
  src/mocks/data/mockBenefits.ts
  src/mocks/data/mockCard.ts
  src/mocks/data/mockCards.ts
  src/mocks/data/mockGrades.ts
  src/mocks/data/mockPartner.ts
  src/mocks/data/mockPartners.ts
  src/pages/CardDetailsPage.vue
  src/pages/search/CheckSearchPage.vue
  src/tests/pages/CardDetailsPage.test.ts
  src/tests/pages/MyCardPage.test.ts
  src/types/Benefit.ts
  src/types/Card.ts
  src/types/Partner.ts
Labels: ⚒️ Refactor

#241 refactor: HomePage 마커 이미지 변경
  src/components/home/KakaoMap.vue
Labels: ⚒️ Refactor

#249 [REFACTOR #248]: 가맹점 정보 페이지 아이콘 추가
  src/components/partner/PartnerInfo.vue
Labels: ⚒️ Refactor

#262 [FEATURE #259]: 지도 검색 바 아래 카테고리 버튼 늘리기
  components.json
  src/components/MenuButton.vue
  src/components/common/SearchBar.vue
  src/components/home/CategoryPillButton.vue
  src/components/home/HomeSearchBar.vue
  src/components/ui/button/index.ts
  src/types/CategoryPill.ts
Labels: ✨ Feature

#264 [FEATURE #261]: 혜택 imageUrl이 없는 경우 표시할 기본 이미지 추가
  src/assets/DEFAULT_BENEFIT_IMAGE.png
  src/components/card/BenefitItem.vue
  src/pages/CardDetailsPage.vue
Labels: ✨ Feature

#270 [BUG #258]: 지도에서 조회 시 파트너 ID가 없는 파트너 상세 조회로 넘어가는 문제
  package-lock.json
  package.json
  src/App.vue
  src/components/partner/PartnerList.vue
  src/components/ui/sonner/Sonner.vue
  src/components/ui/sonner/index.ts
Labels: 🐞 Bug

#276 [FEATURE #265]: 사이트 이름, Favicon 수정, 카드 가로로 나오는 것 세로로
  index.html
  public/favicon.ico
  src/components/card/BenefitItem.vue
  src/components/cardlist/CardItem.vue
Labels: ⚒️ Refactor, ✨ Feature

#278 [FEATURE #277]: pwa 플러그인 설치 및 서비스워커 등록
  package-lock.json
  package.json
  public/icons/icon-192.png
  public/icons/icon-512.png
  src/main.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: ✨ Feature
