Repository payper-devs/payper-client, pull requests merged in 2025-07, with the labels that each got.

#6 [CHORE #5]: 이슈 및 PR 템플릿 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/default_issue.md
  .github/pull_request_template.md
Labels: 🧹 Chore

#9 [DEVOPS #8]: PR 자동 테스트 CI 구성
  .github/workflows/ci.yml
  package.json
  src/components/__tests__/example.test.ts
Labels: 🐳 DevOps

#12 [FEATURE #10]: 테스트 환경 설정
  package-lock.json
  package.json
  src/components/__tests__/example.test.ts
  src/mocks/handlers.ts
  src/mocks/node.ts
  vitest.config.ts
  vitest.setup.ts
Labels: ✨ Feature, 🧪 Test

#21 [FEATURE #19]: 응답 객체 추가 정의
  src/types/Benefit.ts
  src/types/Card.ts
  src/types/Discount.ts
  src/types/Range.ts
Labels: ✨ Feature

#26 [FEATURE #16]: 카드찾기 화면 목록 조회 TDD 생성
  src/api/card.api.ts
  src/mocks/handlers.ts
  src/router/index.ts
  src/tests/CardList.test.ts
  src/tests/MyCardPage.test.ts
  src/tests/example.test.ts
  src/types/Benefit.ts
  src/types/Card.ts
  src/types/CardCompany.ts
  src/types/Cards.ts
  src/types/Category.ts
  src/types/Discount.ts
  src/types/Partner.ts
  src/types/Range.ts
  src/views/CardsPage.vue
Labels: ✨ Feature

#49 [FEATURE #38]: 로그아웃 페이지 구현
  src/tests/LogoutPage.test.ts
  src/utils/storage.ts
  src/views/LogoutPage.vue
Labels: ✨ Feature, 🧪 Test

#55 [FEATURE #27]: 가맹점 상세 조회 페이지 구현
  package-lock.json
  package.json
  src/api/partner.api.ts
  src/pages/PartnerDetailsPage.vue
  src/tests/CardList.test.ts
  src/tests/MyCardPage.test.ts
  src/tests/PartnerPageDetails.test.ts
  src/types/Partner.ts
  src/utils/storage.ts
Labels: ✨ Feature, 🧪 Test

#56 [REFACTOR #53]: 응답 객체 수정
  package-lock.json
  src/router/index.ts
  src/tests/CardDetails.test.ts
  src/tests/CardList.test.ts
  src/tests/CardSearch.test.ts
  src/tests/MyCardPage.test.ts
  src/types/AnnualCost.ts
  src/types/Benefit.ts
  src/types/BenefitGrade.ts
  src/types/Card.ts
  src/types/CardCompany.ts
  src/types/Discount.ts
  src/types/Grade.ts
  src/types/Limit.ts
  src/types/Partner.ts
  src/types/User.ts
  src/views/CardDetailsPage.vue
  src/views/CardListPage.vue
  src/views/MyCardPage.vue
Labels: ⚒️ Refactor

#57 [REFACTOR #29]: views 폴더를 pages 폴더로 통합
  src/pages/CardDetailsPage.vue
  src/pages/CardListPage.vue
  src/pages/LogoutPage.vue
  src/pages/MyCardPage.vue
  src/pages/SettingsPage.vue
  src/router/index.ts
  src/tests/CardList.test.ts
  src/tests/CardSearch.test.ts
  src/tests/MyCardPage.test.ts
  src/tests/pages/CardDetailsPage.test.ts
  src/tests/pages/CardListPage.test.ts
  src/tests/pages/KakaoCallbackPage.test.ts
  src/tests/pages/LandingPage.test.ts
  src/tests/pages/LogoutPage.test.ts
  src/tests/pages/MyCardPage.test.ts
  src/tests/pages/PartnerDetailsPage.test.ts
  src/tests/pages/SettingsPage.test.ts
  src/views/HomeView.vue
Labels: ⚒️ Refactor

#59 [FEATURE #54]: API 함수 및 컴포저블 구현
  src/api/auth.api.ts
  src/api/axios.ts
  src/api/benefit.api.ts
  src/api/card.api.ts
  src/api/mycard.api.ts
  src/api/partner.api.ts
  src/api/user.api.ts
  src/composables/auth.query.ts
  src/composables/benefit.query.ts
  src/composables/card.query.ts
  src/composables/mycard.query.ts
  src/composables/partner.query.ts
  src/composables/useCardQuery.ts
  src/composables/useCardsQuery.ts
  src/composables/useMeQuery.ts
  src/composables/useMyCardsQuery.ts
  src/composables/user.query.ts
  src/mocks/data/mockCard.ts
  src/mocks/data/mockCategory.ts
  src/pages/LandingPage.vue
  src/tests/pages/CardDetailsPage.test.ts
  src/tests/pages/KakaoCallbackPage.test.ts
  src/tests/pages/MyCardPage.test.ts
  src/types/Benefits.ts
  src/types/auth/KakaoLoginRequest.ts
  src/types/auth/LoginResponse.ts
  src/types/auth/NewTokensResponse.ts
  src/types/card/CardSearchOptions.ts
Labels: ⚒️ Refactor, ✨ Feature, 🧪 Test

#64 [FEATURE #63]: 카카오톡 연동
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/KakaoLoginButton.vue
  src/main.ts
  src/mocks/browser.ts
  src/mocks/data/auth/mockLoginResponse.ts
  src/mocks/handlers.ts
  src/pages/KakaoCallbackPage.vue
  src/pages/LandingPage.vue
  src/router/index.ts
  src/tests/pages/KakaoCallbackPage.test.ts
Labels: ✨ Feature, 🔒 Security, 🧪 Test

#67 [FEATURE #37]: 카드 아이템 클릭 시 카드 상세 페이지로 이동 구현
  src/pages/CardListPage.vue
  src/router/index.ts
  src/tests/pages/CardListPage.test.ts
Labels: ✨ Feature

#69 [REFACTOR #62]: 응답 객체에 해당하는 전역 목데이터 작성
  src/mocks/data/mockBenefit.ts
  src/mocks/data/mockBenefits.ts
  src/mocks/data/mockCard.ts
  src/mocks/data/mockCardCompany.ts
  src/mocks/data/mockCards.ts
  src/mocks/data/mockCategories.ts
  src/mocks/data/mockCategory.ts
  src/mocks/data/mockPartners.ts
  src/mocks/data/mockUser.ts
  src/pages/CardDetailsPage.vue
  src/tests/pages/CardDetailsPage.test.ts
  src/types/Limit.ts
Labels: ⚒️ Refactor, 🧪 Test

#70 [FEATURE #60]: MapComponent 구현
  .gitignore
  package-lock.json
  package.json
  src/components/MapComponent.vue
  src/main.ts
Labels: ✨ Feature

#74 [FEATURE #73]: 페이지별 라우팅 설정
  src/App.vue
  src/pages/CardListPage.vue
  src/pages/HomePage.vue
  src/router/index.ts
  src/tests/pages/CardListPage.test.ts
Labels: ✨ Feature, 🧪 Test

#86 [FEATURE #75]: 개발 환경에서 서버 API 호출시 msw로부터 데이터 반환 받도록 설정
  src/mocks/data/mockCards.ts
  src/mocks/data/mockTokens.ts
  src/mocks/handlers.ts
  src/tests/pages/CardListPage.test.ts
Labels: ✨ Feature

#88 [FEATURE #87]: Lucide 아이콘 라이브러리 설치
  src/pages/HomePage.vue
Labels: ✨ Feature

#90 [FEATURE #89]: 컬러 프로필 설정
  src/assets/main.css
  src/pages/HomePage.vue
Labels: ✨ Feature

#96 [FEATURE #95]: MenuButton 구현
  src/components/MenuButton.vue
  src/pages/TestPage.vue
Labels: ✨ Feature

#98 [FEATURE #97]: BottomNavigation 수정
  src/components/common/BottomNavigation.vue
  src/pages/TestPage.vue
  src/tests/components/BottomNavigation.test.ts
Labels: ✨ Feature, 🧪 Test

#102 [FEATURE #99]: LandingPage 구현
  src/App.vue
  src/assets/BrandLogo.vue
  src/assets/KakaoIcon.vue
  src/components/KakaoLoginButton.vue
  src/pages/LandingPage.vue
Labels: ✨ Feature

#107 [FEATURE #104]: MorePage(더보기 페이지) 구현
  src/App.vue
  src/components/MenuButton.vue
  src/components/common/BottomNavigation.vue
  src/pages/LogoutPage.vue
  src/pages/MorePage.vue
  src/pages/SettingsPage.vue
  src/router/index.ts
  src/tests/components/BottomNavigation.test.ts
  src/tests/pages/LogoutPage.test.ts
  src/tests/pages/MorePage.test.ts
Labels: ✨ Feature, 🧪 Test

#110 [FEATURE #109]: ProfilePage.vue 구현
  src/components/profile/UserInfo.vue
  src/pages/ProfilePage.vue
Labels: ✨ Feature

#115 [FEATURE #85]: PartnerDetailsPage 추가 구현
  src/App.vue
  src/api/partner.api.ts
  src/components/common/BottomNavigation.vue
  src/components/common/PageHolder.vue
  src/components/partner/PartnerCard.vue
  src/components/partner/PartnerInfo.vue
  src/mocks/data/mockPartner.ts
  src/mocks/handlers.ts
  src/pages/PartnerDetailsPage.vue
  src/tests/components/BottomNavigation.test.ts
  src/tests/pages/PartnerDetailsPage.test.ts
  src/types/navigation/NavigationItem.ts
  src/types/navigation/NavigationRoutes.ts
Labels: ⚒️ Refactor, ✨ Feature

#116 [FEATURE #111]: CardDetailsPage 추가 구현
  package-lock.json
  package.json
  src/App.vue
  src/assets/main.css
  src/components/card/BenefitDescriptionAccordion.vue
  src/components/card/BenefitItem.vue
  src/components/ui/accordion/Accordion.vue
  src/components/ui/accordion/AccordionContent.vue
  src/components/ui/accordion/AccordionItem.vue
  src/components/ui/accordion/AccordionTrigger.vue
  src/components/ui/accordion/index.ts
  src/mocks/data/mockBenefits.ts
  src/mocks/data/mockCard.ts
  src/mocks/data/mockGrades.ts
  src/pages/CardDetailsPage.vue
  src/tests/pages/CardDetailsPage.test.ts
  tailwind.config.ts
Labels: ⚒️ Refactor, ✨ Feature

#119 [FEATURE #118]: CardDetailsPage에 "내 카드에 추가하기" 버튼 기능 구현
  src/api/mycard.api.ts
  src/composables/mycard.query.ts
  src/pages/CardDetailsPage.vue
Labels: ✨ Feature

#121 [BUG #120]: PartnersByLocation에서 빌드 에러
  .github/workflows/ci.yml
  src/pages/PartnersByLocation.vue
Labels: 🐞 Bug, 🐳 DevOps

#125 [FEATURE #124]: SelectDrawerButton 컴포넌트 구현
  package-lock.json
  package.json
  src/App.vue
  src/components/search/SelectDrawerButton.vue
  src/components/ui/drawer/Drawer.vue
  src/components/ui/drawer/DrawerClose.vue
  src/components/ui/drawer/DrawerContent.vue
  src/components/ui/drawer/DrawerDescription.vue
  src/components/ui/drawer/DrawerFooter.vue
  src/components/ui/drawer/DrawerHeader.vue
  src/components/ui/drawer/DrawerOverlay.vue
  src/components/ui/drawer/DrawerTitle.vue
  src/components/ui/drawer/DrawerTrigger.vue
  src/components/ui/drawer/index.ts
  src/pages/TestPage.vue
Labels: ✨ Feature

#137 [REFACTOR #136]: CreditSearchPage 필터 및 css 수정
  src/pages/search/CreditSearchPage.vue
Labels: ⚒️ Refactor
